export const PATHS = {
  home: "/",
  auth: "/auth",
  resetPassword: "/reset-password",
  dashboard: "/Dashboard",
  koiCompatible: "/KoiCompatible",
  profile: "/profile",
  community: "/community",
  communitySubmit: "/community/submit",
  communityMyPosts: "/community/my-posts",
  partners: "/partners",
  adminPartners: "/adminPartners",
  faqManager: "/FAQManager",
  adminPost: "/AdminPost",
  blog: "/blog",
};
